import type { Metadata } from "next";
import {ThemeProvider} from "@/components/provider/ThemeProvider";
import "./globals.css";
import React from "react";


export const metadata: Metadata = {
  title: "NextBuy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
      >
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
        {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
